
server:
  port: 8083
  servlet:
    context-path: '/api-usuario/'

spring:
  application:
    name: apireserva-usuario-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microsservicos-usuario
    username: postgres
    password: vini4222
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://cxsjvvjz:au7bfHJoqYGYvIfrDjsGuGVLTSw0gYrm@chimpanzee.rmq.cloudamqp.com/cxsjvvjz

apireserva:
  api:
    url:
      reserva: 'http://apireserva-reserva-service'
  broker:
    exchange:
      userEvent: apireserva.eventoDeUsuario

ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
  auth:
    jwtSecret: 5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRfUjX
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
