
server:
  port: 8083
  servlet:
    context-path: '/api-usuario/'

spring:
  application:
    name: apireserva-usuario-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microsservicos-usuario
    username: postgres
    password: vini4222
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://jfjbuyzn:YVA3pFuUdOxbE4_5bL9srQzHY3YwpM4W@moose.rmq.cloudamqp.com/jfjbuyzn

apireserva:
  api:
    url:
      reserva: 'http://apireserva-reserva-service'
  broker:
    exchange:
      userEvent: apireserva.eventoDeUsuario

ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
  auth:
    jwtSecret: VmYq3t6w9z$C&F)H@McQfTjWnZr4u7x!A%D*G-KaNdRgUkXp2s5v8y/B?E(H+MbQ
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
